//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.30 at 09:15:39 AM CEST 
//


package de.inf_schauer.javaCvGui.form;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormRegionElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormRegionElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="top-left-x" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="top-left-y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="bottom-right-x" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="bottom-right-y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormRegionElement")
public class FormRegion {

    @XmlAttribute(name = "top-left-x", required = true)
    protected BigInteger topLeftX;
    @XmlAttribute(name = "top-left-y", required = true)
    protected BigInteger topLeftY;
    @XmlAttribute(name = "bottom-right-x", required = true)
    protected BigInteger bottomRightX;
    @XmlAttribute(name = "bottom-right-y", required = true)
    protected BigInteger bottomRightY;
    @XmlAttribute(name = "class")
    protected String clazz;

    /**
     * Gets the value of the topLeftX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTopLeftX() {
        return topLeftX;
    }

    /**
     * Sets the value of the topLeftX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTopLeftX(BigInteger value) {
        this.topLeftX = value;
    }

    /**
     * Gets the value of the topLeftY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTopLeftY() {
        return topLeftY;
    }

    /**
     * Sets the value of the topLeftY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTopLeftY(BigInteger value) {
        this.topLeftY = value;
    }

    /**
     * Gets the value of the bottomRightX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBottomRightX() {
        return bottomRightX;
    }

    /**
     * Sets the value of the bottomRightX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBottomRightX(BigInteger value) {
        this.bottomRightX = value;
    }

    /**
     * Gets the value of the bottomRightY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBottomRightY() {
        return bottomRightY;
    }

    /**
     * Sets the value of the bottomRightY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBottomRightY(BigInteger value) {
        this.bottomRightY = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

}
