//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.30 at 09:15:39 AM CEST 
//


package de.inf_schauer.javaCvGui.form;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import de.inf_schauer.javaCvGui.form.FormConfiguration;
import de.inf_schauer.javaCvGui.form.FormRegion;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FormConfiguration_QNAME = new QName("", "FormConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FormConfiguration }
     * 
     */
    public FormConfiguration createFormConfiguration() {
        return new FormConfiguration();
    }

    /**
     * Create an instance of {@link FormRegion }
     * 
     */
    public FormRegion createFormRegion() {
        return new FormRegion();
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link TextElement }
     * 
     */
    public TextElement createTextElement() {
        return new TextElement();
    }

    /**
     * Create an instance of {@link VersionIdentificator }
     * 
     */
    public VersionIdentificator createVersionIdentificator() {
        return new VersionIdentificator();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FormConfiguration")
    public JAXBElement<FormConfiguration> createFormConfiguration(FormConfiguration value) {
        return new JAXBElement<FormConfiguration>(_FormConfiguration_QNAME, FormConfiguration.class, null, value);
    }

}
