//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.30 at 09:15:39 AM CEST 
//


package de.inf_schauer.javaCvGui.form;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuestionElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuestionElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Text" type="{}TextElement" minOccurs="0"/>
 *         &lt;element name="FormRegion" type="{}FormRegionElement" minOccurs="0"/>
 *         &lt;element name="Field" type="{}FieldElement" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="response-type" type="{}ResponseType" default="single" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuestionElement", propOrder = {
    "text",
    "formRegion",
    "fields"
})
public class Question {

    @XmlElement(name = "Text")
    protected TextElement text;
    @XmlElement(name = "FormRegion")
    protected FormRegion formRegion;
    @XmlElement(name = "Field", required = true)
    protected List<Field> fields;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "required")
    protected Boolean required;
    @XmlAttribute(name = "response-type")
    protected ResponseType responseType;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link TextElement }
     *     
     */
    public TextElement getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextElement }
     *     
     */
    public void setText(TextElement value) {
        this.text = value;
    }

    /**
     * Gets the value of the formRegion property.
     * 
     * @return
     *     possible object is
     *     {@link FormRegion }
     *     
     */
    public FormRegion getFormRegion() {
        return formRegion;
    }

    /**
     * Sets the value of the formRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormRegion }
     *     
     */
    public void setFormRegion(FormRegion value) {
        this.formRegion = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getFields() {
        if (fields == null) {
            fields = new ArrayList<Field>();
        }
        return this.fields;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRequired() {
        if (required == null) {
            return true;
        } else {
            return required;
        }
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the responseType property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseType }
     *     
     */
    public ResponseType getResponseType() {
        if (responseType == null) {
            return ResponseType.SINGLE;
        } else {
            return responseType;
        }
    }

    /**
     * Sets the value of the responseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseType }
     *     
     */
    public void setResponseType(ResponseType value) {
        this.responseType = value;
    }

}
